; PlatformIO Project Configuration File

[platformio]
default_envs = Remote_Heltec_v2

[env:Remote_Heltec_v2]
framework = arduino
platform = espressif32
board = heltec_wifi_lora_32_V2
build_src_filter = ${dir.remote}
build_flags =
  -w -include "src/boards/heltec-2.h"
lib_deps =
  ${common.lib_deps}
  LoRa
lib_ignore = RadioHead, FlashStorage

[env:Receiver_Heltec_v2]
framework = arduino
platform = espressif32
board = heltec_wifi_lora_32_V2
build_src_filter = ${dir.receiver}
build_flags =
  -include "src/boards/heltec-2.h"
  -w -D RECEIVER_SCREEN
lib_deps =
  ${common.lib_deps}
  LoRa
lib_ignore = RadioHead, FlashStorage

[dir]
remote = +<shared/> +<remote/> -<receiver/>
receiver = +<shared/> -<remote/> +<receiver/>

[common]
lib_deps =
  Wire
  SPI
  Adafruit GFX Library
  Smoothed
